### ISSUE TITLE
access nanny via http proxy fails

### ISSUE THREAD

**Issue by emicklei** [emicklei/nanny#14]
I am accessing the nanny page through a http proxy service (for authentication)
```
https://myproxy.io?url=https://myservice.net/nanny
```
This fails to load the events because it tries to access
```
https://myproxy.io?url=https://myservice.net?nanny&do=events
```
instead of
```
https://myproxy.io?url=https://myservice.net/nanny%3Fdo=events
```

**Comment by emicklei** [comment]
not sure if this needs to be solved by nanny.
I have changed proxy to handle this issue.

**Comment by ErikOnBike** [comment]
I had the same feeling. Could not replicate in my env and wanted to see whether it could be solved by proxy. So the answer seems: yes can be solved by proxy. Might not be the case for all proxies though.

**Comment by emicklei** [comment]
this is a proxy problem
